---
labels:
  - label: "AgentIsInGoal"
    text: "AgentIsInGoal"

# constants:
#   - constant: "prop_slippery_turn"
#     type: "double"
#     value: "9/9"
#     overwrite: True

probabilities:
  - probability: "FaultProbability"
    value: 0.2
  - probability: "ProbForwardIntended"
    value: 0.1
  - probability: "ProbTurnIntended"
    value: 0.1
  
modules:
  - module: "Agent"
    commands:
      - action: "[Agent_turn_left]"
        guard: "AgentIsOnSlippery"
        update: "True"
        overwrite: True
        index: 3
      - action: "[Agent_turn_right]"
        guard: "AgentIsOnSlippery"
        update: "True"
        overwrite: True
        index: [0,1]
...